TOKEN = '5997480587:AAHDMpfgj-sUXkjfnES_umWbLgQU1AR4H_s'
mongo_database = 'tgbot'
places_collection = 'places'
users_collection = 'users'
admins_collection = 'admins'
posts_collection = 'posts'
support = 'https://t.me/durahan'
username = "dAKB4phxFx"
password = "EIamC1W3jw"
bucket = "gmihtt-tgbot"
main_admins = {381873540, 138769502}
